# Generated by Django 5.0.1 on 2024-02-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
