# Generated by Django 5.0.1 on 2024-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_catalog', '0002_employees_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='employees_pictures'),
        ),
    ]
